// Kartoteki dostawców kartonów — OvocxMalinovi
// Źródło: dane publiczne (KRS, strony www) + dane własne do uzupełnienia
// Wygenerowano: 2026-02-26

window.DOSTAWCY_DATA = {
  wygenerowano: '2026-02-26',
  dostawcy: [
    {
      id: 'TFP',
      nazwa: 'TFP Sp. z o.o.',
      skrot: 'TFP',
      adres: 'ul. Katowicka 26, Dziećmierowo',
      miasto: 'Kórnik',
      kod_pocztowy: '62-035',
      kraj: 'Polska',
      nip: '781-000-02-02',
      krs: '0000039932',
      www: 'https://tfp.com.pl',
      telefon: '+48 61 897 23 00',
      email: 'opakowania@tfp.com.pl',
      kontakt_os: '',
      uwagi: 'Producent tektury falistej i opakowań kartonowych od 1992 r. Trzy zakłady: Kórnik/Dziećmierowo (siedziba), Babimost, Śrem. Dział sprzedaży tektury: tektura@tfp.com.pl.',
      aktywny: true,
      kolor: '#f59e0b'
    },
    {
      id: 'OPAK',
      nazwa: 'OPAK SERVICE Sp. z o.o.',
      skrot: 'OPAK',
      adres: 'ul. Przybyszewskiego 176/178',
      miasto: 'Łódź',
      kod_pocztowy: '93-120',
      kraj: 'Polska',
      nip: '728-10-00-709',
      krs: 'do uzupełnienia',
      www: 'https://opakservice.pl',
      telefon: '+48 42 689 09 11',
      email: 'zapytanie@opakservice.pl',
      kontakt_os: '',
      uwagi: 'Producent opakowań kartonowych i tekturowych z Łodzi. Uwaga: zweryfikuj czy to właściwy kontrahent — w Polsce wiele firm z "OPAK" w nazwie.',
      aktywny: true,
      kolor: '#3b82f6'
    },
    {
      id: 'KRAFT_BOX',
      nazwa: 'Kraft-Box Sp. z o.o.',
      skrot: 'KRAFT BOX',
      adres: 'ul. Łąkowa 3A',
      miasto: 'Kowalew',
      kod_pocztowy: '63-300',
      kraj: 'Polska',
      nip: '608-010-80-90',
      krs: '0000503233',
      www: 'https://kraft-box.eu',
      telefon: '+48 62 768 79 10',
      email: 'do uzupełnienia',
      kontakt_os: '',
      uwagi: 'Producent opakowań z tektury falistej i standów, 20+ lat na rynku, Laureat Diamentów Forbesa. Email — kontakt przez formularz na stronie: kraft-box.eu/en/contact/',
      aktywny: true,
      kolor: '#8b5cf6'
    },
    {
      id: 'STORAENSO',
      nazwa: 'Stora Enso Poland S.A.',
      skrot: 'STORAENSO',
      adres: 'ul. Aleja Wojska Polskiego 21',
      miasto: 'Ostrołęka',
      kod_pocztowy: '07-401',
      kraj: 'Polska',
      nip: '758-000-06-92',
      krs: '0000073313',
      www: 'https://www.storaenso.com',
      telefon: 'do uzupełnienia',
      email: 'do uzupełnienia',
      kontakt_os: '',
      uwagi: 'Główny zakład produkcyjny w Polsce (S.A.) — celuloza, papier, tektura falista. Dodatkowe zakłady opakowań: Tychy, Mosina, Łódź. Podmiot handlowy: Stora Enso Polska Sp. z o.o., ul. M. Kasprzaka 6, Warszawa. Kontakt przez formularz: storaenso.com/en/contact-us',
      aktywny: true,
      kolor: '#059669'
    },
    {
      id: 'SAICA',
      nazwa: 'Saica Pack Bydgoszcz Sp. z o.o.',
      skrot: 'SAICA',
      adres: 'Poledno 2A',
      miasto: 'Bukowiec (k. Bydgoszczy)',
      kod_pocztowy: '86-122',
      kraj: 'Polska',
      nip: '559-181-86-10',
      krs: '0000008996',
      www: 'https://www.saica.com',
      telefon: 'do uzupełnienia',
      email: 'do uzupełnienia',
      kontakt_os: '',
      uwagi: 'Dawniej Schumacher Packaging — przejęty przez Saica Group w październiku 2024 r. Drugi zakład: Saica Pack Wrocław Sp. z o.o., ul. Wrocławska 66, Krępice, 55-330 Miękinia, tel. +48 71 397 71 00. Kontakt przez saica.com.',
      aktywny: true,
      kolor: '#dc2626'
    },
    {
      id: 'EUROBOX',
      nazwa: 'Eurobox Polska Sp. z o.o. (Dunapack Packaging)',
      skrot: 'EUROBOX',
      adres: 'Przesiadłów 1',
      miasto: 'Ujazd',
      kod_pocztowy: '97-225',
      kraj: 'Polska',
      nip: '526-220-75-78',
      krs: '0000031057',
      www: 'https://www.dunapack-packaging.com',
      telefon: '+48 44 734 10 01',
      email: 'do uzupełnienia',
      kontakt_os: '',
      uwagi: 'Producent tektury falistej i opakowań kartonowych od 1998 r. Część Dunapack Packaging / Prinzhorn Group. Drugi zakład: Lubliniec. Certyfikaty: ISO 9001, ISO 14001, BRC AA, FSC.',
      aktywny: true,
      kolor: '#0284c7'
    },
    {
      id: 'KENKEL',
      nazwa: 'Kenkel Wojciech — Wytwórnia Opakowań',
      skrot: 'KENKEL',
      adres: 'ul. Boszkowska 1',
      miasto: 'Grotniki',
      kod_pocztowy: '64-140',
      kraj: 'Polska',
      nip: '697-000-75-72',
      krs: 'CEIDG',
      www: 'https://wojciechkenkel.pl',
      telefon: '+48 65 537 04 39',
      email: 'opakowaniawk@post.pl',
      kontakt_os: 'Wojciech Kenkel',
      uwagi: 'Jednoosobowa działalność gospodarcza, producent opakowań z tektury falistej od 1991 r. (Wielkopolska). Ekologiczny: 100% energia odnawialna, FSC. Kom.: +48 665 050 616.',
      aktywny: true,
      kolor: '#7c3aed'
    },
    {
      id: 'INNY',
      nazwa: 'Inny dostawca — do uzupełnienia',
      skrot: 'INNY',
      adres: '',
      miasto: '',
      kod_pocztowy: '',
      kraj: 'Polska',
      nip: '',
      krs: '',
      www: '',
      telefon: '',
      email: '',
      kontakt_os: '',
      uwagi: 'Kartoteka do ręcznego uzupełnienia.',
      aktywny: true,
      kolor: '#6b7280'
    }
  ]
};
